### ISSUE TITLE
First Page @ pdf

### ISSUE THREAD

**Issue by CoolZeroNL** [yzane/vscode-markdown-pdf#145]
Is it possible to generate a first page, that have no footer of header ?

**Comment by ksmarty** [comment]
Bump

I've been struggling with this as well

**Comment by owanerwo** [comment]
Bump, I'm also looking for an option to omit header and footer on the first page.

I've tried:
```css
@page :first {
    margin-top: 0cm;
    margin-bottom: 0cm;
}
```
to hide header and footer under custom content, however it turns out that the setting was applied to every page, not just the first.
