### ISSUE TITLE
Inline code blocks do not use a proportional font

### ISSUE THREAD

**Issue by azixMcAze** [yzane/vscode-markdown-pdf#26]
Hello,

Inline code `like this` do not use a proportional font when converted to PDF, contrary to the markdown preview in VSCode as you can see:
![markdown-pdf_inline_code_font](https://user-images.githubusercontent.com/1919205/28250429-4ec5dda2-6a68-11e7-908f-5a21551ca8fc.png)

It seems that `font-family: inherit` in  `markdown-pdf.css` causes the problem:
```css
/* for inline code */
:not(pre):not(.hljs) > code {
	color: #A31515;
	font-size: inherit;
	font-family: inherit; 
}
```
