### ISSUE TITLE
the `:has()` selector doesn't affect the pdf

### ISSUE THREAD

**Issue by marifcelik** [yzane/vscode-markdown-pdf#347]
i have `style.css` file in the project root folder and i setted the `"markdown-pdf.styles": [ "style.css" ]`. i use this css code to center all images
```css
p:has(img) {
  text-align: center;
}
```
other css selectors works but the `:has` selector doesn't seem to work.
